version: "3"

services: 
  two-factor-api:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - /app/node_modules
      - .:/app  
    ports: 
      - "5000:5000"  
    depends_on: 
      - mongodb
    environment: 
      - MONGO_URI=mongodb://admin:password@mongodb

  mongodb:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=two-factor
    volumes: 
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081" 
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
     - ME_CONFIG_BASICAUTH_USERNAME=admin
     - ME_CONFIG_BASICAUTH_PASSWORD=admin123456    

volumes: 
  mongo-data:
    driver: local
         